### ISSUE TITLE
nuhkoca.com wrong domain name

### ISSUE THREAD

**Issue by maliyaman** [nuhkoca/nuhkoca.com#3]
hi Nuh , While browsing your page, I noticed that the site is on the wrong domain and wanted to let you know. Congratulations on your great work.

**Comment by nuhkoca** [comment]
Hey @maliyaman 

Yeah I am aware of that for a long time but unfortunately couldn't yet purchase another domain for me. Nowadays, thinking of getting another one and hope I'll fix it. Thanks for the heads-up, I appreciate it!
